### ISSUE TITLE
sample is not working

### ISSUE THREAD

**Issue by dolphinsd** [couchbaselabs/couchbase-net-beersample#1]
Fresh instal of couchbase - working
Install and run this sample - not working - does not return any results, only can add news items! Please advise.

**Comment by jeffrymorris** [comment]
@vladsd  -

I need to update this project to the latest and work on the documentation; I'll try to get to it next week.

Thanks,

Jeff

**Comment by jeffrymorris** [comment]
@vladsd  -

I updated the project to the 2.0.1 release and N1QL DP3. The Beers controller uses the Beer-Sample bucket, so make sure you install it. The Breweries controller uses N1QL DP3, to have it work you need to download and install N1QL DP3 and associate the N1QL service with your couchbase instance: 

./cbq-engine -couchbase http://<coucbhase-server-name>:8091/

On or around February 3rd, we will release 2.0.2 with support for N1QL DP4, once it's a available I'll update the code to use it as well.

Thanks,

Jeff

**Comment by vladsd** [comment]
Thanks, will try

**Comment by vladsd** [comment]
Ok, getting error about view that is not supported:
10:59:56.520873 Info line disabled false
10:59:56.629946 tuqtng started...
10:59:56.629946 version: v0.7.2
10:59:56.629946 site: http://localhost:8091/
11:00:10.844887 ←[31mERROR: Unable to access view - cause: error executing view
req at http://127.0.0.1:8092/beer-sample/_all_docs?limit=1001: 400 Bad Request -
 {"error":"bad_request","reason":"_all_docs is no longer supported"}
←[0m←[2m -- couchbase.(*viewIndex).ScanRange() at view_index.go:186←[0m
11:00:10.845888 Checking bucket URI: /pools/default/buckets/beer-sample?bucket_u
uid=ce8f7779fd3b11c6322811b725982e8e
11:00:10.845888 ←[31mERROR: Get /pools/default/buckets/beer-sample?bucket_uuid=c
e8f7779fd3b11c6322811b725982e8e: unsupported protocol scheme ""←[0m←[2m -- couch
base.(*viewIndex).ScanRange() at view_index.go:192←[0m

**Comment by jeffrymorris** [comment]
@vladsd -

What version of CB?

-Jeff

**Comment by vladsd** [comment]
3.0.2-1603

**Comment by jeffrymorris** [comment]
@vladsd -

That is from the couchbase server logs, correct? The actual beer sample application should work at least for the "beers" controller.

-Jeff

**Comment by MikeGoldsmith** [comment]
Hi @dolphinsd 

I know this is way out of date, but wanted to let you know I've updated the repository to be compatible with the latest Couchbase Server (including RBAC in 5.0+).

I'm going to close this issue too. Let me know if I can be of any further help.
